### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by jimrandomh**
This pullrequest contains only refactoring, no features or fixes. My medium-term plan is to (among other things) make it so that all the hotkeys are configurable. That requires, first, getting the menu and hotkey-handling code to a point where I can comprehend it and make large changes. Hence refactoring.

 - Hotkeys, popups and menus are split out from D3DProxyDevice.cpp into their own files
 - Common idioms with strings, popups and menu drawing are nicer and denser
 - Relatively low risk of having broken things

Because this moves things into different files and has some find/replace-style changes, it will generate merge conflicts with just about everything. Hence making a pull request immediately, rather than waiting until there's actual feature-work behind it.

### CODE REVIEW

**Comment by baggyg** [comment]
Hi James, 

Good stuff. Simon and I will look through and merge when comfortable and familiar with everything here. In terms of testing have you fully tested these changes? Have you also ensured this doesn't cause an issue with the device reset calls (this is usually what breaks first)? 

Grant

**Comment by jimrandomh** [comment]
Not very thoroughly tested; just compiling and going through the menus. If something is broken, it'll probably be either a format string in a relatively-uncommon popup or debug message (those got shuffled around a fair bit), or the project file. (I'm using a newer version of Visual Studio, which wanted to make non-backwards-compatible changes to the project files, so I hand-edited to add references to the new files rather than checking in its changed versions.)

**Comment by baggyg** [comment]
OK, we are prob sending out a release this weekend. Once that is done I will do some testing and then we can merge.

**Comment by jimrandomh** [comment]
Definitely don't merge right before the release - I'm not testing nearly that much!

This set of patches introduces "hotkey expressions", and centralizes all the hotkeys from D3DProxyDevice::HandleControls into one place and makes them nicer to read. It also cleans up a few hundred lines of copy-paste damage to support later changes. The next area of focus will be how configs are handled, to support complex config entries (for keybindings with alternatives and modifiers) and programmatic handling of large numbers of them.

**Comment by jimrandomh** [comment]
This batch of commits includes:
 * Performance optimization in shader register handling, which the profiler said was slow, for a couple percent framerate increase.
 * Refactors config-file management, eliminating a lot of really weird string handling and cutting SaveConfig from seven lines per setting down to one.
 * Further refactors menus, to the point where the individual menus' code looks reasonably nice.
 * Other miscellaneous refactoring to make the code shorter and more readable
It's possible that this introduced bugs. The most likely place where bugs can be found, is menu items not having a reasonable cooldown or having an adjustment-rate that's the wrong order of magnitude.

**Comment by baggyg** [comment]
So the release is out, so we can start to test and look to merge. Unfortunately we have lost the ability to  automatically merge. Hopefully this is simple. I will prob look to bring this into an official fork and go from there since that should allow me to see the conflicts and test easier. I am away from Thusday for just over 2 weeks so doubt I will be able to do anything in that time. I will also talk with Simon and see if he has any plans for testing / merging. However looking at the refactors it certainly looks cleaner so we are keen to merge before next release.

**Comment by jimrandomh** [comment]
It's only a few commits behind; I'll take care of merge conflicts and bring it up to date with the head version later today.

**Comment by DrBeef** [comment]
Hi James

Is your fork up to date with all the changes in the master? If so then I'll
merge from your fork into a test branch in the Perception repo over the
weekend, once confirmed that everything works ok (the biggest concern is
the device reset), then I'll merge from there into the master.

Once that is done, I'd like to also update to using the latest version of
the OVR SDK, suspect that might be a bit fiddly, so if you have some
changes in-flight, bear this in mind. However, I doubt it would introduce
any merge conflicts as I expect it will be in different parts of the
codebase.

Regards
Simon

**Comment by DrBeef** [comment]
Merged into a branch called jimrandomh for testing.

All looking good so far, 32 and 64 bit no issues that I can see, device
reset is fine (can alt+tab to desktop and back to game without it throwing
a wobbly).

**Comment by jimrandomh** [comment]
Yes, it's up to date with master.

As far as testing, the thing most likely to have broken, would be one of the menus: something like a menu-setting which doesn't apply its change when adjusted, or adjusts at a rate that's the wrong order of magnitude.

**Comment by jimrandomh** [comment]
From here forward the changes are going to be less refactoring and more functionality-oriented. For the menus in particular, I plan to:
 * Make a proper navigation-stack for menus
 * Redo the menu vertical-position/selection handling to be less fiddly
 * Make UI for entering complex hotkey specifications, like "Shift+R or both triggers"
 * Move all builtin hotkeys into the menu config system

After that I'm going to dive into the perspective-handling. In particular, I'm going to try to figure out how to get the correct FOV and distortion scale from the Oculus SDK. This is a little tricky because there's a three-way interplay to untangle between FOV, distortion scale, and aspect ratio, and some of the FOV numbers floating around are horizontal FOVs while others are diagonal FOVs. (In particular, I believe games mostly use horizontal FOV, while Oculus mostly uses diagonal FOV.)

**Comment by jimrandomh** [comment]
One other thing that's at risk of having been broken is the shader-config menus, which have special cases in them dealing with scrolling that I haven't been testing.

**Comment by DrBeef** [comment]
Hi

The only issue I've found is with the shader menus as you predicted. If I
scroll too far, then all the shader hashes vanish, and I have to scroll
back up some way to get them to re-appear.

I think it will be quicker if you could take a look at the branch and
propose the fix, once that is working again correctly I'll merge everything
back to the master.

On the whole those, it's very nice. Simplified a lot of stuff, and your use
of Lambda Expressions/Anonymous Functions is pretty neat.

Let me know when you've got it working, and we'll get it merged to master,

Thanks
Simon

**Comment by jimrandomh** [comment]
I tested with the current version and couldn't replicate the scrolling issue. Could you check the latest revision (6f3d8e6) and see if it's still there? (The way scrolling works was redone in 8edf098, which might've fixed it.)

**Comment by jimrandomh** [comment]
Major changes since last time:
 * Most of the adjuster hotkeys are configurable, and default unbound.
 * The HUD/GUI quick-set and sub-menu link are merged
 * Convergence is both a distance setting and a toggle, default off, since it's for 3D monitors not for HMDs.

**Comment by baggyg** [comment]
Hi James, 

Sorry I haven't been able to give more feedback. I am currently travelling but will be back in a week or so. I know that Simon is currently working hard to get this branch going and then merged to the master one, which we can then all work from. I can see there are many improvements here, which is great. 

However we need to keep control of this and hit one milestone at a time. Looking into the latest version I am concerned that all the hotkeys are by default unbound. This is going to be unintuitive for new users. Having them configurable is brilliant but a user should just be able to pick up and play, and then get into configuring once they are used to the software. We also need to make sure the menus are intuitive, for example in the current version the hotkeys are linked to the section they are in. So for example the comfort mode hotkey is in the comfort mode section. I am not sure it works well to remove it from here. I would be keen to know all the devs thoughts.

We also need to get to a stage where we have the main master branch up to date and fully tested with all initial functionality changes agreed, working and correct. I know at the moment you have your own fork, as well as a branch Simon setup. Although I am impressed by your speed and work can I suggest we all focus on getting that merged in the first instance before you move on? Things like the scrolling issue on the shader analyzer need to be verified fixed and that may be hard to do when there is not an easy way to isolate the changes on your fork from other changes that we should all agree on is the right direction, before committing.

Once we have a solid base we are all happy with we can discuss how things should change. It is vital that we all decide the direction functionality, and that we have agreed before moving things forward. Please don't take this as a negative, as as I said the new functionality is looking great. With any Open Source project we just need to make sure we have shared goals and plans.

**Comment by Enterfrize** [comment]
Looks like we have some growing pains on our hands!  We've never had so many talented developers on Vireio before.  I've been seeing a lot of updates to Vireio which is good to see; now we have to figure out how to coordinate all this.

I know Grant and Simon have connected in Skype before.  James, are you a member of MTBS?  Get yourself registered, and we can start to PM each other (my user name is Neil).

You seem to be very serious about helping out with Vireio, so let's catch up.

Regards,
Neil

**Comment by jimrandomh** [comment]
I agree that the defaults should probably be set to the hotkeys as they
were in previous versions, at least initially. For a lot of them, for
example black smear correction, currently the only way to adjust the
setting is by hotkey; what I envision is having a menu item which leads
into a sub-menu where you can both set the setting it directly, and bind
hotkeys to toggle it, and getting all that and the resetting-to-default and
such handled in a way that scales cleanly with large numbers of settings.
There are definitely decisions to be made about menu organization; this is
not something I've thought through yet, but it is now in a state where
moving things around and making new sub-menus is easy and free of traps.

I'm going to be quite busy with other things over the weekend, but if
anyone wants to talk on Skype, Tuesday afternoon would be a good time (my
username is jimrandomh).

On May 1, 2015 10:36 AM, "Grant Bagwell" <notifications@github.com> wrote:

>
> Hi James,
>
> Sorry I haven't been able to give more feedback. I am currently
travelling but will be back in a week or so. I know that Simon is currently
working hard to get this branch going and then merged to the master one,
which we can then all work from. I can see there are many improvements
here, which is great.
>
> However we need to keep control of this and hit one milestone at a time.
Looking into the latest version I am concerned that all the hotkeys are by
default unbound. This is going to be unintuitive for new users. Having them
configurable is brilliant but a user should just be able to pick up and
play, and then get into configuring once they are used to the software. We
also need to make sure the menus are intuitive, for example in the current
version the hotkeys are linked to the section they are in. So for example
the comfort mode hotkey is in the comfort mode section. I am not sure it
works well to remove it from here. I would be keen to know all the devs
thoughts.
>
> We also need to get to a stage where we have the main master branch up to
date and fully tested with all initial functionality changes agreed,
working and correct. I know at the moment you have your own fork, as well
as a branch Simon setup. Although I am impressed by your speed and work can
I suggest we all focus on getting that merged in the first instance before
you move on? Things like the scrolling issue on the shader analyzer need to
be verified fixed and that may be hard to do when there is not an easy way
to isolate the changes on your fork from other changes that we should all
agree on is the right direction, before committing.
>
> Once we have a solid base we are all happy with we can discuss how things
should change. It is vital that we all decide the direction functionality,
and that we have agreed before moving things forward. Please don't take
this as a negative, as as I said the new functionality is looking great.
With any Open Source project we just need to make sure we have shared goals
and plans.

**Comment by jimrandomh** [comment]
I do have an MTBS account, but would prefer to stick to email (
jimrandomh@gmail.com) and maybe Skype, rather than try to introduce another
messaging system into my habits.

**Comment by baggyg** [comment]
Hi James,

I am finally back home and now in a position to test and hopefully get this refactoring merged. Can you tell me where is the best version to try (your fork directly or the branch Simon had prepared to manage the merge)? If it is your fork then have you integrated the fixes Simon did on that branch here (i.e. the positional whilst rotated fix)? 

Can you also tell me the current state? I.e. Are you aware of any bugs / features outstanding? I see you have added defaults, is the shader analyser bug fixed? 

Kind Regards

Grant

**Comment by jimrandomh** [comment]
I haven't merged DrBeef's changes in, but the merge looks like it should be pretty simple. The shader-menu bug should be fixed. I'll have time to merge tomorrow evening; in the mean time I'd suggest this branch as the main one to test. I wouldn't make a user-facing release yet, but I believe this is in reasonable condition to merge into master.

Areas with known issues that weren't there before:

 * Cooldowns: Sometimes you intend to press a button once but it registers twice. I'm going to get rid of the whole cooldown thing and replace it with edge triggers, so don't bother with tweaks in the mean time.
 * Help text on the world-scale and convergence adjusters doesn't scroll.

Things that haven't been tested, but should be:

 * Any devices other than DK2 or games other than Skyrim
 * What happens when you load config files from older versions

Areas where there were pre-existing issues closely related to code touched by this branch, that should be addressed eventually:

 * Missing menu items for advanced setting. For things like DK2 black smear, before, you could toggle it by hard-coded hotkey but couldn't change it through the menu. Now you can change the hotkey through the menu, but can't change the setting directly. The intent is to have a menu item that changes the setting directly, grouped together with a setting to assign it a hotkey.
 * You can reset individual settings to default, but there's no global reset-to-default or highlighting of non-default settings
 * Menu hotkeys and game hotkeys can overlap, making the menu awkward to use since the game responds to the same keystrokes. It'd be nice if it intercepted the game's API calls to hide those keystrokes, and perhaps do some key-mapping as well (to fill the role people currently use XPadder for).
 * Drawing menus and popups is really slow. Profiling suggests something in the texture setup is sending the video card drivers onto a slow path.
 * The aesthetics of the menu could be a lot better

**Comment by DrBeef** [comment]
Few small comments:


   - What happens when you load config files from older versions

I wouldn't be overly concerned about this. Until now the intention is that
people just take the new configuration, since it will have often changed
between releases.


   - Drawing menus and popups is really slow. Profiling suggests something
   in the texture setup is sending the video card drivers onto a slow path.

That's consistent with things like the FPS counter and other popups causing
a severe FPS drop.. this has been around for some time this one. Would be
nice to resolve this issue somehow.. however doesn't seem to be the case
with all games, just some more so than others (or at least, not so severe
with others).


If you are able to merge in the changes I made on the jimrandomh branch I
would appreciate it, once you've done that to your fork I'll deprecate that
branch as it will be much more straightforward going from your fork into
Master directly once it is ready.

Last thing.. is it still possible to disable all of Vireio's hot-keys?, the
last release added that functionality with a double click on right-control,
quite a useful feature for games with a lot of potentially interfering
hot-keys.

Best regards
Simon

**Comment by jimrandomh** [comment]
Changes are merged, and I confirm that the position-tracking+roll fix works. Testing a bit more, there seem to be two issues outstanding.

One, hotkey-cooldown handling seems to have regressed. Rather than diagnose the regression, I think the right thing is to plow ahead and make the hotkeys be edge-triggered.
Two, missing keybinding settings in the game profile config are still defaulting to unbound, rather than using the defaults defined in HandleGameProfile.

**Comment by DrBeef** [comment]
Good stuff!, thanks for merging in the changes, that means I can drop that
temporary branch now.

If you are going to be adding edge triggering issue #1 isn't worth
resolving.
Number 2 sounds like it needs to be fixed though by the sounds of it.

I've not recently tested the changes in your fork, will hopefully get a
chance to do so tonight.

**Comment by jimrandomh** [comment]
In the process of implementing edge-triggering, I figured out the true cause of the slow menu rendering and several other mysteries.

Menu drawing is done either on Present (right after StereoView does its compositing), BeginScene or EndScene depending on the game type (m_deviceBehavior.whenToRenderVPMENU, set in D3DProxyDevice::VPMENU_UpdateSettings), and changeable with LAlt+Up. In the case of Skyrim, this is EndScene(). But it turns out that Skyrim doesn't call EndScene only once per frame, or a consistent number of times; it calls it twice per frame in the menu menu, about ten times per frame in-game. Perception was re-drawing the menu for each call, multiplying the computational cost of drawing the menus by about 10x. It was also updating the cooldowns and menu-border animation once per call, which meant that these were wildly different speeds in different contexts.

The way this patch does hotkey edge-triggering threw the problem into sharp relief, because IsPressed() works by checking whether the key is currently pressed, and wasn't pressed in the previous frame. So if the menu gets handled multiple times in the same frame (without updating the input in between), then each press of the arrow keys while move the selection multiple times.

The right place to draw the menu is actually none of the three options that were available. The right place is in Present(), immediately before StereoView does its compositing. If my understanding is correct, this should happen exactly once, and should work for all games, eliminating the need for game-specific configuration of this option and the need for a hotkey.

This patchset:
 * Makes hotkeys edge-triggered
 * Makes VPMENU always draw right before compositing, rather than any of the game-specific places it drew before. This fixes the framerate problems with menus, popups, and the framerate counter.
 * Makes the config-file loader use proper defaults for any settings that were missing from the config

It is possible that the menu-handling change broke compatibility with a game I haven't tested. This is unlikely, but if it had happened, the symptom would either be that menus and popups weren't visible, OR that in the menu, pressing the up/down arrows moved the selection multiple times instead of only once.

**Comment by jimrandomh** [comment]
I see there're some more changes in master. Keep in mind that automatic merging with this branch mostly doesn't work at all; the only way to safely merge changes is to go through those diffs and reapply each change by hand, which is a pain. The sooner we can get this branch folded into master, the less of that there'll be.

**Comment by baggyg** [comment]
Agreed. Well done for finding out about the menu and odd that some games are calling end scene more than once per cycle. I have just downloaded this now and am testing. I will let you know what I find. I also have a lot of changes locally that are not committed but will wait until this is merged to sync them

**Comment by baggyg** [comment]
Hi James, 
Right had a good test through. All looking very good actually. Only a few minor niggles. 
Disconnected Screen View - This didn't seem to be assigned by default. I also think it can be moved from the Overall Settings screen to the hotkey section. 
The text on the World Scale screen doesn't show. This is not too much of a issue as I think this screen can be removed anyway and just have a World Scale Figure somewhere (we can pick this up post merge). 
The Page Down no longer works in the menu. I tried to use this on the shaders screen. It used to skip 10 rows or so. 

However I think this can be merged straight away (or once you have Simon's latest changes). We can then work together on things before the next release. Post merge there are some changes we can make:
1) Remove convergence option if stereotype > 100
2) Remove World Scale in lieu of figure
3) Perhaps an advanced toggle in the config file to show debugging hotkeys. The general user doesn't need all the current options (Render states / cube textures / etc). 

Let me know when it is ready to automatically merge and I'll press the button :-)

**Comment by jimrandomh** [comment]
Disconnected screen view being unbound: The issue seems to be that default values are effectively defined in two places: In Shared/ProxyHelper.cpp, and Release/Perception/cfg/profiles.xml. (It used to be much more than two places, so this is progress.) The catch is that, because configurable keybindings can now support having multiple keys at once, several things that were bound to a hardcoded key combination plus a configurable value, are now instead bound to a configurable value which includes that hardcoded key combination in the default, but the default was only updated in one of the two remaining places.

I'm going to rewrite config.xml so that, in each game profile, only settings which have non-default values are mentioned. (Settings which are omitted will get the default value specified in ProxyHelper.cpp.)

World scale screen text: That was using the same variables/infrastructure as the menu selection, which got rewritten. Will come up with a more elegant solution to the instructions-in-menus issue later. (There are other places besides the World Scale and Convergence menus that would benefit from that.)

Page down: This was an oversight when redoing menu-selection handling; I'll add it back in.

Re Advanced toggle/debugging hotkeys: I'd just put them in an "Advanced" submenu where they're out of the way. Many of those options would be better served by menu items that toggle them, rather than menu items that set hotkeys that toggle them, so that's also something to change.

**Comment by jimrandomh** [comment]
I believe this is merge-able. Future development I do, will be on a different branch.

**Comment by baggyg** [comment]
Hi James, 
I couldn't seem to find your e-mail. 
Could you possibly have a look at the latest commit I put on the main master file, please? I am constructing a new menu that will contain a lot of collected things. At the moment I am just trying to change the world scale to be a simple figure based adjuster. However whenever I am in this menu, adjusting this always goes up hugely fast. The other menus don't seem to have the issue, so I have probably done something stupid but can't seem to see what that is. 
Thanks in advance

Grant

**Comment by jimrandomh** [comment]
My email's jimrandomh@gmail.com. I think the trick is that ViewAdjustment::ChangeWorldScale is doing something counterintuitive - rather than setting the world scale, it adds to the world scale.

**Pull request merged**
